#!/bin/bash
# shellcheck disable=SC2024
# (SC2024: redirect on `sudo -u postgres pg_dump ... > file` happens in
# the calling shell, not under sudo. We run as root via cron, so root's
# shell handles the redirect and has write access to $STAGING. The
# postgres process inherits the open FD. Correct as-written.)
#
# Dump the app-facing tables of the osm schema for fast restore.
#
# What this captures (and why):
#   - osm.highways              — what CTM queries; 261M+ rows
#   - osm.admin_boundaries      — for area selection
#   - osm.exclusion_areas       — golf courses, military, etc.
#   - any other osm.* tables EXCEPT the middle tables below
#
# What this excludes (and why):
#   - osm.planet_osm_ways       — osm2pgsql middle table; only needed for
#                                 incremental replication, not for serving
#                                 traffic. Regenerated by osm2pgsql import.
#   - osm.planet_osm_rels       — same; middle table.
#
# This matches the proven dump pattern used by
# scripts/osm/refresh-osm-template.sh in the color-the-map repo, which has
# been in use for syncing prod osm data to dev.
#
# Pairs with osm-checkpoint.sh (replication sequence). Together, the two
# enable two restore paths:
#
#   - QUICK (app continuity, ~1-3 hours): pg_restore this dump, app serves
#     traffic. Replication is broken but data is current as of last backup.
#
#   - FULL (replication working, ~hours): osm2pgsql import from the
#     filtered PBF in /mnt/backup/osm-bootstrap/, then resume replication
#     from the saved sequence number. Regenerates the middle tables and
#     flat-nodes.bin.
#
# Usage: osm-tables-dump.sh <staging-dir>
# Output: <staging-dir>/osm/osm-tables.dump

set -euo pipefail

STAGING="${1:-/var/lib/backup-staging}/osm"
DB=${OSM_DB:-color-the-map}
COMPRESS=${OSM_DUMP_COMPRESS:-3}
PG_SUDO=${PG_SUDO-sudo -u postgres}

mkdir -p "$STAGING"

OUTPUT="$STAGING/osm-tables.dump"

echo "  dumping osm schema (excluding middle tables)..."
$PG_SUDO pg_dump \
    -d "$DB" \
    --schema=osm \
    --exclude-table=osm.planet_osm_ways \
    --exclude-table=osm.planet_osm_rels \
    --format=custom \
    --compress="$COMPRESS" \
    > "$OUTPUT"

if [ ! -s "$OUTPUT" ]; then
    echo "ERROR: osm dump file is empty or missing: $OUTPUT" >&2
    exit 1
fi

SIZE=$(du -h "$OUTPUT" | cut -f1)
echo "OSM tables dump complete: $SIZE"
